name: Create Scratch Org
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Salesforce CLI
        run: |
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
          echo "export PATH=$PWD/sfdx/bin:\$PATH" >> ~/.bashrc
          source ~/.bashrc
          sfdx --version
      - name: Authenticate to Salesforce Org
        env:
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_TOKEN: ${{ secrets.SF_TOKEN }}
        run: |
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SF_CLIENTID }} --jwtkeyfile server.key --username $SF_USERNAME --password $SF_PASSWORD --setdefaultdevhubusername --instanceurl https://login.salesforce.com --setalias DevHub
      - name: Create Scratch Org
        run: |
          sfdx force:org:create -f config/project-scratch-def.json -a scratch-org-1 -s -v DevHub -d 30 -w 10 -e "Enterprise"
      - name: Deploy Metadata
        run: |
          sfdx force:source:push -u scratch-org-1
